[[stack]]
name = "CHANGE_MEProduction"
stack_class = "acru_l.stacks.LucarioStack"

[stack.config]
hosted_zone_domain_name = "apex.domain"
cert_export_name = "CertExportName"
version = "0.0.0"
vpc_name = "SomeStackName/VPC/SomeName"

[stack.config.rds_config]
db_name = "CHANGE_ME_db"
db_username = "CHANGE_ME"
add_proxy = true
multi_az = true
deletion_protection = true
setup_alarms = true
#instance_class = "BURSTABLE3"
#instance_size = "MICRO"

[stack.config.service_config]
domain_name = "api.apex.domain"
project_source_path = "./src/"
health_check_url = "https://api.apex.domain/"
secrets = [
    {name = "SecretKey", arn_key = "SECRET_KEY_ID", password_length = 32, include_space = false, exclude_punctuation = true},
    {name = "DefaultAdminPassword", arn_key = "DEFAULT_ADMIN_PASSWORD_ID", password_length = 16, include_space = false, exclude_punctuation = true},
]
[stack.config.service_config.environment]
STAGE = "production"
WSGI_APPLICATION = "CHANGE_ME.wsgi.application"
MANAGE_PY_PATH = "CHANGE_ME/manage.py"
SITE_DOMAIN = "api.apex.domain"
DJANGO_SETTINGS_MODULE="CHANGE_ME.settings"
DEFAULT_ADMIN_EMAIL="admin+prod@apex.domain"

[stack.config.service_config.pre_deploy_config]
source_path = "./.aws/pre_deploy"
properties = {app_label = "db", migration_name = "0001"}
[stack.config.service_config.post_deploy_config]
source_path = "./.aws/post_deploy"
properties = {app_label = "db", migration_name = "0001"}
