coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        # advanced
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: False
        only_pulls: false
