version: '3.7'

volumes:
  {{ cookiecutter.src_package_name }}_postgres_data: {}

services:
    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - published: 7777
              target: 8025
              protocol: tcp

    postgres:
        image: mdillon/postgis:11
        volumes:
            - {{ cookiecutter.src_package_name }}_postgres_data:/var/lib/postgresql/data
        env_file:
            - dev/dev.env
        ports:
            - published: 5433
              target: 5432
              protocol: tcp
