{% raw %}name: Production
on:
  release:
    types: [created]

env:
  STAGE: production
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  release:
    name: Deploy to production
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      #----------------------------------------------
      #       install and configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'{% endraw %}
      #----------------------------------------------
      #              Collect Statics
      #----------------------------------------------
      - name: Collect statics
        run: poetry run src/{{ cookiecutter.src_package_name }}/manage.py collectstatic --noinput --settings={{ cookiecutter.src_package_name }}.settings
      #----------------------------------------------
      #                 Compress
      #----------------------------------------------
      - name: Compress statics
        run: poetry run src/{{ cookiecutter.src_package_name }}/manage.py compress --force --settings={{ cookiecutter.src_package_name }}.settings{% raw %}
      #----------------------------------------------
      #                 Requirements
      #----------------------------------------------
      - name: Collect Requirements
        run: poetry export -o src/requirements.txt --without-hashes
      #----------------------------------------------
      #                  deploy
      #----------------------------------------------
      # TODO: add cdk app deploy{% endraw %}
